# Generated by Django 3.2.14 on 2022-07-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='excerpt',
            field=models.TextField(blank=True),
        ),
    ]
